name: flutter_bluetooth_printer_platform_interface
description: Plugin platform interface for flutter_bluetooth_printer plugin.
version: 0.0.4
repository: https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin/packages/flutter_bluetooth_printer_platform_interface

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter: